steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/math-chatbot-484411/cloud-run-source-deploy/math-chatbot:latest
  _SUPABASE_URL: ""
  _SUPABASE_ANON_KEY: ""
